sonar.projectKey=jeronymo42_qa-auto-engineer-python-project-241
sonar.organization=jeronymo42
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/tests/**,**/test_*.py
sonar.coverage.exclusions=**/tests/**,**/test_*.py


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=qa-auto-engineer-python-project-241
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
